import keyword
from importlib.resources import files
from pathlib import Path
from typing import Optional

import cv2 as cv

from guimauve.models.data import Data
from guimauve.models.model import ModelError
from guimauve.models.variant import ImageVariant
from guimauve.workspace import DataWorkspace

HEADER = """\
# Generated by `guimauve data sync` — DO NOT EDIT BY HAND.
# Any change will be overwritten on the next sync.
from guimauve.metaclass.metadata import MetaData
from guimauve.models.element import Element
from guimauve.models.replay import Replay

ALIAS = {alias!r}
"""

CLASS = """\


class {classname}(metaclass=MetaData, model={model}, alias=ALIAS):
{body}
"""


def _render_entries(entries: dict, model: str) -> str:
    if not entries:
        return "    pass"
    lines = []
    for name, entry in entries.items():
        if not name.isidentifier() or keyword.iskeyword(name):
            raise ValueError(f"{name!r} is not a valid Python identifier")
        lines.append(f"    {name} = {model}.from_dict({entry.to_dict(json_mode=True)!r})")
    return "\n".join(lines)


def render_module(data: Data, alias: str) -> str:
    return (
        HEADER.format(alias=alias)
        + CLASS.format(classname="Elements", model="Element", body=_render_entries(data.elements or {}, "Element"))
        + CLASS.format(classname="Replays", model="Replay", body=_render_entries(data.replays or {}, "Replay"))
    )


def _module_path(alias: str):
    return files("guimauve") / "data" / f"{alias}.py"


def sync_dataset(workspace: DataWorkspace, alias: str) -> Optional[ModelError]:
    data = Data.from_file(workspace.data_file(alias))  # construct, no validation
    if errors := data.resolve():  # net : missing image, bad key...
        return ModelError(alias, errors)

    _remove_orphaned_images(workspace, alias, data)
    _module_path(alias).write_text(render_module(data, alias), encoding="utf-8")

    return None


def _remove_orphaned_images(workspace: DataWorkspace, alias: str, data: Data) -> None:
    referenced = {
        Path(variant.path).resolve()
        for element in (data.elements or {}).values()
        for variant in (element.variants or {}).values()
        if isinstance(variant, ImageVariant)
    }

    images_dir = workspace.images_dir(alias)
    if not images_dir.is_dir():
        return

    # remove unreferenced files
    for path in images_dir.rglob("*"):
        if path.is_file() and path.resolve() not in referenced:
            path.unlink()

    # remove now-empty directories (deepest first)
    for path in sorted(images_dir.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def sync_all(workspace: DataWorkspace) -> dict[str, ModelError]:
    aliases = set(workspace.datasets())

    data_dir = files("guimauve") / "data"
    for module in data_dir.glob("*.py"):
        if module.stem != "__init__" and module.stem not in aliases:
            module.unlink()

    failures = {}
    for alias in aliases:
        if error := sync_dataset(workspace, alias):
            failures[alias] = error
    return failures


def remove_module(alias: str) -> None:
    path = _module_path(alias)
    if path.is_file():
        path.unlink()


def save_element(workspace: DataWorkspace, alias: str, element) -> None:
    data = Data.from_file(workspace.data_file(alias))
    if data.elements is None:
        data.elements = {}

    name = element.name

    for variant_name, variant in (element.variants or {}).items():
        if isinstance(variant, ImageVariant) and variant.image is not None:
            path = workspace.image_path(alias, name, variant_name)
            path.parent.mkdir(parents=True, exist_ok=True)
            cv.imwrite(str(path), cv.cvtColor(variant.image, cv.COLOR_RGB2BGR))
            variant.path = path
            variant.image = None  # free the ndarray

    data.elements[name] = element
    data.to_file(workspace.data_file(alias))
