from pynput.keyboard import Key as Key_
from pynput.keyboard import KeyCode
from pynput.mouse import Button as Mouse_

from guimauve.enums import Button, Key

KEY_MAP = {
    Key.ALT: Key_.alt_l,
    Key.ALT_R: Key_.alt_r,
    Key.BACKSPACE: Key_.backspace,
    Key.CAPS_LOCK: Key_.caps_lock,
    Key.CTRL: Key_.ctrl_l,
    Key.CTRL_R: Key_.ctrl_r,
    Key.DELETE: Key_.delete,
    Key.END: Key_.end,
    Key.ENTER: Key_.enter,
    Key.ESC: Key_.esc,
    Key.HOME: Key_.home,
    Key.INSERT: Key_.insert,
    Key.MEDIA_PLAY_PAUSE: Key_.media_play_pause,
    Key.MEDIA_NEXT: Key_.media_next,
    Key.MEDIA_PREVIOUS: Key_.media_previous,
    Key.MEDIA_VOLUME_MUTE: Key_.media_volume_mute,
    Key.MEDIA_VOLUME_DOWN: Key_.media_volume_down,
    Key.MEDIA_VOLUME_UP: Key_.media_volume_up,
    Key.META: Key_.cmd_l,
    Key.META_R: Key_.cmd_r,
    Key.NUM_LOCK: Key_.num_lock,
    Key.PAGE_UP: Key_.page_up,
    Key.PAGE_DOWN: Key_.page_down,
    Key.PAUSE: Key_.pause,
    Key.PRINT_SCREEN: Key_.print_screen,
    Key.SCROLL_LOCK: Key_.scroll_lock,
    Key.SHIFT: Key_.shift_l,
    Key.SHIFT_R: Key_.shift_r,
    Key.SPACE: Key_.space,
    Key.SUPER: Key_.cmd_l,
    Key.SUPER_R: Key_.cmd_r,
    Key.TAB: Key_.tab,
    Key.DOWN: Key_.down,
    Key.LEFT: Key_.left,
    Key.RIGHT: Key_.right,
    Key.UP: Key_.up,
    Key.KP_0: KeyCode.from_vk(96),
    Key.KP_1: KeyCode.from_vk(97),
    Key.KP_2: KeyCode.from_vk(98),
    Key.KP_3: KeyCode.from_vk(99),
    Key.KP_4: KeyCode.from_vk(100),
    Key.KP_5: KeyCode.from_vk(101),
    Key.KP_6: KeyCode.from_vk(102),
    Key.KP_7: KeyCode.from_vk(103),
    Key.KP_8: KeyCode.from_vk(104),
    Key.KP_9: KeyCode.from_vk(105),
    Key.KP_ENTER: Key_.enter,
    Key.F1: Key_.f1,
    Key.F2: Key_.f2,
    Key.F3: Key_.f3,
    Key.F4: Key_.f4,
    Key.F5: Key_.f5,
    Key.F6: Key_.f6,
    Key.F7: Key_.f7,
    Key.F8: Key_.f8,
    Key.F9: Key_.f9,
    Key.F10: Key_.f10,
    Key.F11: Key_.f11,
    Key.F12: Key_.f12,
    Key.A: "a",
    Key.B: "b",
    Key.C: "c",
    Key.D: "d",
    Key.E: "e",
    Key.F: "f",
    Key.G: "g",
    Key.H: "h",
    Key.I: "i",
    Key.J: "j",
    Key.K: "k",
    Key.L: "l",
    Key.M: "m",
    Key.N: "n",
    Key.O: "o",
    Key.P: "p",
    Key.Q: "q",
    Key.R: "r",
    Key.S: "s",
    Key.T: "t",
    Key.U: "u",
    Key.V: "v",
    Key.W: "w",
    Key.X: "x",
    Key.Y: "y",
    Key.Z: "z",
    Key.COMMA: ",",
    Key.DOT: ".",
    Key.SEMICOLON: ";",
    Key.COLON: ":",
    Key.SLASH: "/",
    Key.BACKSLASH: "\\",
    Key.QUOTE: "'",
    Key.DOUBLE_QUOTE: '"',
    Key.MINUS: "-",
    Key.UNDERSCORE: "_",
    Key.PLUS: "+",
    Key.EQUAL: "=",
}

MOUSE_MAP = {
    Button.LEFT: Mouse_.left,
    Button.RIGHT: Mouse_.right,
    Button.MIDDLE: Mouse_.middle,
}
